# Python Libraries

Numpy

Pandas

Matplotlib

Seaborn

scikit-learn

Numpy: allows to perform advanced mathematical and statistical operations on the object.
       It provides vectorization of mathematical operations on arrays and matrices.
        Pandas built on numpy.
        
Maplotlib: allows to perform Visualizations.(plotting library in Python)

scikit-learn: It provides Machine learning algorithms: classification, regression, clustering, model validation
    

#To install packages

pip install package name

conda install package name

In [1]:
#Numpy:
#Creating Numpy Arrays 

import numpy as np
array_1d=np.array([11,22,33,44,55])# 1 dimensional array
array_2d=np.array ([[10,20,30],[40,50,90]]) # 2 dimensional array
print(array_1d)
print(array_2d)

[11 22 33 44 55]
[[10 20 30]
 [40 50 90]]


In [2]:
#Find Shape of the array
array_2d.shape[1]

3

In [3]:
array_1d.shape

(5,)

In [4]:
#Number of Dimensions
print(array_2d.ndim)
print(array_1d.ndim)

2
1


In [5]:
##creating numpy array using numpy.arange

array_1=np.arange(5)
array_1

array([0, 1, 2, 3, 4])

In [6]:
#creating numpy array using numpy.arange

array_2=np.arange(2,10,2) ##(start,end,step)
array_2

array([2, 4, 6, 8])

In [7]:
##creating numpy array using numpy.linspace
#generates linear evenly spaced elements between the start and the end

array_3=np.linspace(0,0.75,4)
array_3

array([0.  , 0.25, 0.5 , 0.75])

In [8]:
##Numpy array creation via various functions

##numpy.zeros, numpy.ones, numpy.eye, nrandom.rand, numpy.random.randn, and numpy.empty.

##numpy.ones
# Produces 3x2 array of 1's.
array_4=np.ones((2,3))
array_4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
##numpy.zeros
# Produce 3X4 array of zeros.
array_5=np.zeros((2,3))
array_5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
print(array_4+array_5)
print(array_4 *array_5)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#Day 4

In [12]:
arra=np.eye(3)
arra

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
##numpy.random.rand
##Using the rand, randn functions
#rand(m) produces uniformly distributed random numbers with range 0 to m

np.random.seed(200)   # Set seed
array_8=np.random.rand(4)
array_8

array([0.94763226, 0.22654742, 0.59442014, 0.42830868])

In [14]:
arra2=np.diag((2,3,6))
arra2

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 6]])

In [15]:
##numpy.empty
##creating uninitialised array
#numpy.empty(shape)
import numpy as np
array_10=np.empty((4,3))
array_10

array([[1.30897177e-311, 2.86558075e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 3.69776220e-062],
       [7.11820420e-091, 2.49020403e+180, 2.81080270e-033],
       [1.20941024e+161, 6.48224659e+170, 5.82471487e+257]])

In [16]:
arr_11=np.array([10,11,12,13])
print(arr_11.dtype)
print(type(arr_11))

int32
<class 'numpy.ndarray'>


In [17]:
##default dtype in NumPy is float.
#change the data type 
arr_11=arr_11.astype(float)
arr_11.dtype

dtype('float64')

In [18]:
##NumPy indexing and slicing

##Array indices in NumPy start at 0

#import numpy as np
arr_1 = np.arange(6)

#print entire array
arr_1

array([0, 1, 2, 3, 4, 5])

In [19]:
arr_1[2]

2

In [20]:
arr_1[:]

array([0, 1, 2, 3, 4, 5])

In [21]:
arr_1[2:5]

array([2, 3, 4])

In [22]:
#last element
arr_1[-1]

5

In [23]:
##Modify value at arr_1[1]
arr_1[1] = 8
arr_1

array([0, 8, 2, 3, 4, 5])

In [24]:
array_2d

array([[10, 20, 30],
       [40, 50, 90]])

In [25]:
#[row,column]
array_2d[1,2]

90

In [26]:
array_2d[0:2]

array([[10, 20, 30],
       [40, 50, 90]])

In [27]:
array_2d

array([[10, 20, 30],
       [40, 50, 90]])

In [28]:
array_2d[0:2][0:1,2]

array([30])

In [29]:
array_2d[0:2,0:2]

array([[10, 20],
       [40, 50]])

In [30]:
array_3=np.array ([[10,20,30],[40,50,90],[35,65,76],[90,80,70],[23,34,56]])
array_3

array([[10, 20, 30],
       [40, 50, 90],
       [35, 65, 76],
       [90, 80, 70],
       [23, 34, 56]])

In [31]:
#extract the value 80
array_3[3,1]

80

In [32]:
#extract the 2nd position row and 1st column values
array_3[2,1]

65

In [33]:
#extract 2nd position column values
array_3[:,2]

array([30, 90, 76, 70, 56])

# Introduction to Pandas

Pandas is a powerful package in Python. It is used for Data cleaning and manipulating data to get summary insights from the data.

Pandas is basically used to manipulate tabular data, it is ability select columns and filter rows sort data and do groupby tasks

Pandas has two Data structures: Series and DataFrame

Series: One dimensional labeled array (Capable of holding any data type). The axis labels are called index.
    Create Series by using pandas: pandas.Series(data, index)                                                )
DataFrame: Two dimensional array

#To intall packages
pip install package name
!pip install package name (Jupyter notebook)
conda install package name

In [34]:
import pandas as pd
from pandas import Series,DataFrame

In [35]:
#Creating a Series object
#General syntax is:
#s= Series(data,index)   (or)
#s=pd.Series(data,index)

In [36]:
#Series from a list
S=Series([1,2,3,4,5])
print(S)
print (S[0])
print (S[2])
print(S.values)
print(S.index)
print (list(S.index))
S[5]=6


0    1
1    2
2    3
3    4
4    5
dtype: int64
1
3
[1 2 3 4 5]
RangeIndex(start=0, stop=5, step=1)
[0, 1, 2, 3, 4]


In [37]:
S=Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(S)
print(S[0])
print(S['b'])
S.index

a    1
b    2
c    3
d    4
e    5
dtype: int64
1
2


Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [38]:
print(S)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [39]:
#Adding one element to the series
S['g']=7
print(S)

a    1
b    2
c    3
d    4
e    5
g    7
dtype: int64


In [40]:
#add 1 to each element in 's'
s=pd.Series([8,9,10])
print(s)
S=s+1
print(type(s))
S

0     8
1     9
2    10
dtype: int64
<class 'pandas.core.series.Series'>


0     9
1    10
2    11
dtype: int64

In [41]:
#Deleting elements from a series
#drop(index)
series1=s.drop(1)
series1

0     8
2    10
dtype: int64

In [42]:
#More than one element from a series
series2=Series([8,9,10],index=['h','i','j'])
print(series2)
series3=series2.drop(['i','j'])
print(series3)

h     8
i     9
j    10
dtype: int64
h    8
dtype: int64


In [43]:
#Series from a dictionary
d={'a':3,'b':4}
d1=Series(d)
d1

a    3
b    4
dtype: int64

In [44]:
#We can make changes to a series in place also
d1['a']=8
d1

a    8
b    4
dtype: int64

# Pandas DataFrame

#Creating a dataframe

#From a dictionary of lists, dictionaries, series

#From a list of dictionaries

In [45]:
#create empty dataframe
D=DataFrame()
D

Empty DataFrame
Columns: []
Index: []

In [46]:
D1=pd.DataFrame()
D1

Empty DataFrame
Columns: []
Index: []

In [47]:
#Dictionary of lists
d={'Price':[19,22,13,54,65],'Sales':[600,756,587,859,990]}
frame1=DataFrame(d)
print(frame1)

   Price  Sales
0     19    600
1     22    756
2     13    587
3     54    859
4     65    990


In [48]:
#Dictionary of dictionaries
d1={'Price':{'r1':19,'r2':22},'Sales':{'r1':600,'r2':756}}
frame2=DataFrame(d1)
print(frame2)

    Price  Sales
r1     19    600
r2     22    756


In [123]:
#Dictionary of Series
d2={'Price':Series([19,22,13,54,65]),'Sales':Series([600,756,587,859,990])}
frame3=DataFrame(d2)
print(frame3)


   Price  Sales
0     19    600
1     22    756
2     13    587
3     54    859
4     65    990


Price  Sales
0     19    600
1     22    756
2     13    587

In [50]:
#list of Dictionaries
list1=[{'Price':19,'Sales':600,'Qty':30},{'Price':22,'Sales':756,'Qty':65}]
frame4=DataFrame(list1)
print(frame4)

   Price  Qty  Sales
0     19   30    600
1     22   65    756


In [51]:
#rename(columns={'oldname1':'newname1','oldname2':'newname2'})
frame1.rename(columns={'Price':'Base_Price','Sales':'Unit Sales'},inplace=True)
frame1

Base_Price  Unit Sales
0          19         600
1          22         756
2          13         587
3          54         859
4          65         990

In [52]:
frame4.rename(columns={'Price':'Base_Price','Qty':'Quantity','Sales':'Unit Sales'})


Base_Price  Quantity  Unit Sales
0          19        30         600
1          22        65         756

In [53]:
frame4

Price  Qty  Sales
0     19   30    600
1     22   65    756

# loc and iloc

loc method is label-based, which means that you have to specify rows and columns based on their row and column labels.

iloc is integer index based, so you have to specify rows and columns by their integer index.

In [54]:
#.loc  label index
#.iloc integer index.

print(frame1)
frame1.iloc[0]
frame1.loc[2]

   Base_Price  Unit Sales
0          19         600
1          22         756
2          13         587
3          54         859
4          65         990


Base_Price     13
Unit Sales    587
Name: 2, dtype: int64

In [55]:
print(frame2)
frame2.loc['r1']

    Price  Sales
r1     19    600
r2     22    756


Price     19
Sales    600
Name: r1, dtype: int64

In [56]:
frame1.loc[0]

Base_Price     19
Unit Sales    600
Name: 0, dtype: int64

In [57]:
frame2.iloc['r1']

TypeError: Cannot index by location index with a non-integer key

In [58]:
#extract the value 756 from frame1
frame1.iloc[1]['Unit Sales']

756

In [59]:
#extract 587 from frame1
frame1.loc[2]['Unit Sales']

587

In [60]:
d3={'col1':Series([1,2,3]),'col2':Series([6,7,8])}
frame3=DataFrame(d3)
frame3

col1  col2
0     1     6
1     2     7
2     3     8

In [61]:
#extract more than one element
frame3.iloc[[1,0]]

col1  col2
1     2     7
0     1     6

In [62]:
df1=DataFrame({'price':[23,45,67],'sales':[3,6,7]},index=['a','b','c'])

In [63]:
df1.loc['a']

price    23
sales     3
Name: a, dtype: int64

In [64]:
df1.loc[['a','c']]

price  sales
a     23      3
c     67      7

In [65]:
df1.iloc[[0,1]]

price  sales
a     23      3
b     45      6

In [66]:
df1.iloc[[0]]['sales']

a    3
Name: sales, dtype: int64

In [67]:
#all values from the sales column
df1.iloc[:,[1]]

sales
a      3
b      6
c      7

# Zip function

In [68]:
list1=['first','second','third','fourth']
list2=[56,7,8,9]
list(zip(list1,list2))

[('first', 56), ('second', 7), ('third', 8), ('fourth', 9)]

In [69]:
zipped=list(zip(list1,list2))

In [70]:
#data=list(zipped)

In [71]:
data=pd.DataFrame(zipped,columns=['class','marks'])

In [72]:
print(data)
print(type(data))

    class  marks
0   first     56
1  second      7
2   third      8
3  fourth      9
<class 'pandas.core.frame.DataFrame'>


#Day 5
# Importing Data in Python


#Load CSV file

In [73]:
#path of the file
path="https://s3.us-east-2.amazonaws.com/datafaculty/Store.csv"

In [74]:
#reading a file
import pandas as pd
data=pd.read_csv(path)

In [75]:
type(data)

pandas.core.frame.DataFrame

In [76]:
#view data
data.head(2)

Unnamed: 0  Row ID        Order ID Order Date   Ship Date     Ship Mode  \
0           0       1  CA-2013-152156  11/9/2013  11/12/2013  Second Class   
1           1       2  CA-2013-152156  11/9/2013  11/12/2013  Second Class   

  Customer ID Customer Name   Segment        Country  ... Postal Code Region  \
0    CG-12520   Claire Gute  Consumer  United States  ...       42420  South   
1    CG-12520   Claire Gute  Consumer  United States  ...       42420  South   

        Product ID   Category Sub-Category  \
0  FUR-BO-10001798  Furniture    Bookcases   
1  FUR-CH-10000454  Furniture       Chairs   

                                        Product Name   Sales Quantity  \
0                  Bush Somerset Collection Bookcase  261.96        2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.94        3   

   Discount    Profit  
0       0.0   41.9136  
1       0.0  219.5820  

[2 rows x 22 columns]

In [77]:
#Number of observations(Number of rows, number of cols)
data.shape

(9994, 22)

In [78]:
#number of rows
print(data.shape[0])
#number of cols
print(data.shape[1])

9994
22


In [79]:
#all observations
data

Unnamed: 0  Row ID        Order ID  Order Date   Ship Date  \
0              0       1  CA-2013-152156   11/9/2013  11/12/2013   
1              1       2  CA-2013-152156   11/9/2013  11/12/2013   
2              2       3  CA-2013-138688   6/13/2013   6/17/2013   
3              3       4  US-2012-108966  10/11/2012  10/18/2012   
4              4       5  US-2012-108966  10/11/2012  10/18/2012   
5              5       6  CA-2011-115812    6/9/2011   6/14/2011   
6              6       7  CA-2011-115812    6/9/2011   6/14/2011   
7              7       8  CA-2011-115812    6/9/2011   6/14/2011   
8              8       9  CA-2011-115812    6/9/2011   6/14/2011   
9              9      10  CA-2011-115812    6/9/2011   6/14/2011   
10            10      11  CA-2011-115812    6/9/2011   6/14/2011   
11            11      12  CA-2011-115812    6/9/2011   6/14/2011   
12            12      13  CA-2014-114412   4/16/2014   4/21/2014   
13            13      14  CA-2013-161389   12/6/2013  12/11/2013   
14            14      15  US-2012-118983  11/22/2012  11/26/2012   
15            15      16  US-2012-118983  11/22/2012  11/26/2012   
16            16      17  CA-2011-105893  11/11/2011  11/18/2011   
17            17      18  CA-2011-167164   5/13/2011   5/15/2011   
18            18      19  CA-2011-143336   8/27/2011    9/1/2011   
19            19      20  CA-2011-143336   8/27/2011    9/1/2011   
20            20      21  CA-2011-143336   8/27/2011    9/1/2011   
21            21      22  CA-2013-137330  12/10/2013  12/14/2013   
22            22      23  CA-2013-137330  12/10/2013  12/14/2013   
23            23      24  US-2014-156909   7/17/2014   7/19/2014   
24            24      25  CA-2012-106320   9/25/2012   9/30/2012   
25            25      26  CA-2013-121755   1/16/2013   1/20/2013   
26            26      27  CA-2013-121755   1/16/2013   1/20/2013   
27            27      28  US-2012-150630   9/17/2012   9/21/2012   
28            28      29  US-2012-150630   9/17/2012   9/21/2012   
29            29      30  US-2012-150630   9/17/2012   9/21/2012   
...          ...     ...             ...         ...         ...   
9964        9964    9965  CA-2013-146374   12/6/2013  12/11/2013   
9965        9965    9966  CA-2013-146374   12/6/2013  12/11/2013   
9966        9966    9967  CA-2013-146374   12/6/2013  12/11/2013   
9967        9967    9968  CA-2014-153871  12/12/2014  12/18/2014   
9968        9968    9969  CA-2014-153871  12/12/2014  12/18/2014   
9969        9969    9970  CA-2014-153871  12/12/2014  12/18/2014   
9970        9970    9971  CA-2012-103772   6/28/2012    7/2/2012   
9971        9971    9972  CA-2012-103772   6/28/2012    7/2/2012   
9972        9972    9973  CA-2013-130225   9/12/2013   9/18/2013   
9973        9973    9974  US-2013-103674   12/7/2013  12/11/2013   
9974        9974    9975  US-2013-103674   12/7/2013  12/11/2013   
9975        9975    9976  US-2013-103674   12/7/2013  12/11/2013   
9976        9976    9977  US-2013-103674   12/7/2013  12/11/2013   
9977        9977    9978  US-2013-103674   12/7/2013  12/11/2013   
9978        9978    9979  US-2013-103674   12/7/2013  12/11/2013   
9979        9979    9980  US-2013-103674   12/7/2013  12/11/2013   
9980        9980    9981  US-2012-151435    9/6/2012    9/9/2012   
9981        9981    9982  CA-2014-163566    8/4/2014    8/7/2014   
9982        9982    9983  US-2013-157728   9/23/2013   9/29/2013   
9983        9983    9984  US-2013-157728   9/23/2013   9/29/2013   
9984        9984    9985  CA-2012-100251   5/17/2012   5/23/2012   
9985        9985    9986  CA-2012-100251   5/17/2012   5/23/2012   
9986        9986    9987  CA-2013-125794   9/30/2013   10/4/2013   
9987        9987    9988  CA-2014-163629  11/18/2014  11/22/2014   
9988        9988    9989  CA-2014-163629  11/18/2014  11/22/2014   
9989        9989    9990  CA-2011-110422   1/22/2011   1/24/2011   
9990        9990    9991  CA-2014-121258   2/27/2014    3/4/20

In [80]:
#last 2 observations
data.tail(2)

Unnamed: 0  Row ID        Order ID Order Date  Ship Date  \
9992        9992    9993  CA-2014-121258  2/27/2014   3/4/2014   
9993        9993    9994  CA-2014-119914   5/5/2014  5/10/2014   

           Ship Mode Customer ID Customer Name   Segment        Country  ...  \
9992  Standard Class    DB-13060   Dave Brooks  Consumer  United States  ...   
9993    Second Class    CC-12220  Chris Cortes  Consumer  United States  ...   

     Postal Code Region       Product ID         Category Sub-Category  \
9992       92627   West  OFF-PA-10004041  Office Supplies        Paper   
9993       92683   West  OFF-AP-10002684  Office Supplies   Appliances   

                                           Product Name   Sales Quantity  \
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.60        4   
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.16        2   

      Discount  Profit  
9992       0.0  13.320  
9993       0.0  72.948  

[2 rows x 22 columns]

In [81]:
#Other way to load csv file in Python
#import os module to connect os to Python environment
import os
#Checking of current working directory
os.getcwd()

'C:\\Users\\Nithya'

In [82]:
#Changing working directory
os.chdir("D://Files")
os.getcwd()

'D:\\Files'

In [83]:
#read Store.csv file
Flight=pd.read_csv('FlightDelays.csv')

In [84]:
Flight.head(2)

schedtime carrier  deptime dest  distance        date  flightnumber origin  \
0       1455      OH     1455  JFK       184  01-01-2004          5935    BWI   
1       1640      DH     1640  JFK       213  01-01-2004          6155    DCA   

   weather  dayweek  daymonth  tailnu   delay  
0        0        4         1  N940CA  ontime  
1        0        4         1  N405FJ  ontime

In [85]:
Flight.shape

(2201, 13)

#txt file (tab separated file)
#read_table() helps to read txt file

In [86]:
d=pd.read_table('sample1.txt')
d.head()

C:\Users\Nithya\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


Age Customer   Income Location
0   30        A     1200       A1
1   32        B     1333       A2
2   33      NaN  Missing      NaN

In [87]:
sample=pd.read_csv('sample1.txt',sep ='\t')
sample.head(2)

Age Customer Income Location
0   30        A   1200       A1
1   32        B   1333       A2

In [88]:
print(os.getcwd())
#candidates.csv stores in "D://Files//Files1"
#pd.read_csv("Files1//candidates.csv")
#pd.read_csv("Files2//contributions.csv")

D:\Files


In [89]:
#read xlsx files

In [90]:
e=pd.read_excel("Loandetails.xlsx")
e.head(2)

id  member_id  loan_amnt  funded_amnt  funded_amnt_inv  int_rate  \
0  54734      80364      25000        25000         19419.94    0.1189   
1  55742     114426       7000         7000          6549.40    0.1071   

   installment grade sub_grade  is_inc_v   accept_d    issue_d loan_status  
0       829.10     B        B4      True 2009-07-26 2009-08-05  Fully Paid  
1       228.22     B        B5     False 2008-05-12 2008-05-27  Fully Paid

In [91]:
e.shape

(11825, 13)

In [92]:
os.listdir("D://Files")

['.RData',
 '.Rhistory',
 '1__RA3mCS30Pr0vUxbp25Yxw.png',
 '5th April - Basic Python.zip',
 '5th April - Store.csv',
 '5th April - wines.xlsx',
 'advanced stat.R',
 'Adv_Hyp_GradedAssignmentSol_1.docx',
 'Airlines_Data-1.csv',
 'amesterdem.csv',
 'amesterden.csv',
 'amsterdam.json',
 'audit.csv',
 'Automobile data.csv',
 'Automobile_data.csv',
 'barley.csv',
 'Baseball.csv',
 'BH.csv',
 'boston_prices.csv',
 'Business Statistics - Non Graded Assignment.xlsx',
 'Campaign_File.txt',
 'Canada.xlsx',
 'candidates.csv',
 'Cars_Retail_Price.xlsx',
 'categoricalprofile.csv',
 'City.ipynb',
 'class.docx',
 'classifiers.R',
 'comey.csv',
 'continousprofiles.csv',
 'contributions.csv',
 'copy.txt',
 'corr_matrix_incl_anno_double.png',
 'Credit Card - SAS Functions.csv',
 'Credit.csv',
 'credit.csv-data dictionary.xlsx',
 'credit_history.csv',
 'Cricket_Data-2.xlsx',
 'customers.xlsx',
 'Data Dic_oj.xlsx',
 'Data Quality Report.csv',
 'Data Visualization Graded Case Study Dataset.xlsx',
 'dataqua

In [93]:
#read json files
ams=pd.read_json("amsterdam.json")
ams.head(3)

host_listings_count  accommodates  bathrooms  bedrooms  guests_included  \
0                   1.0             6        1.0       2.0                1   
1                   1.0             2        1.0       1.0                1   
10                  1.0             2        1.0       1.0                1   

    minimum_nights  number_of_reviews  calculated_host_listings_count  \
0                3                  4                               1   
1                2                 17                               1   
10               3                  0                               1   

      price   latitude  longitude        room_type instant_bookable  
0   $145.00  52.361173   4.866755  Entire home/apt                f  
1    $88.00  52.370237   4.859507  Entire home/apt                f  
10  $130.00  52.371424   4.848644  Entire home/apt                f

In [94]:
ams.iloc[:,[1]].head(2)

accommodates
0             6
1             2

In [95]:
ams['accommodates'].head(2)  #it returns series object

0    6
1    2
Name: accommodates, dtype: int64

In [96]:
type(ams['accommodates'])

pandas.core.series.Series

In [97]:
ams[['accommodates']].head(2) # returns DataFrame object

accommodates
0             6
1             2

In [98]:
type(ams[['accommodates']])

pandas.core.frame.DataFrame

In [99]:
#Export csv file
ams.to_csv("E://copies//new1.csv")
#Excel file
ams.to_excel("E://copies//new1.xlsx")
#txt file
ams.to_csv("E://copies//new1.txt",sep='\t')

In [100]:
# Data frame built on series object

#Exercises:
Exercise 1: Create a DataFrame that looks like this:

  Apple    Banana
  
0   30      21
1   15      31

In [ ]:
d={'Apple':[30,15],'Banana':[21,31]}
d1=pd.DataFrame(d)
d1

In [ ]:
#2.a
mydict = [{'p': 2, 'q': 3, 'r': 4, 's': 5},
           {'p': 20, 'q': 30, 'r': 40, 's': 50},
           {'p': 200, 'q': 300, 'r': 400, 's': 500 }]
    
#create data frame from the given dictionary 
d2=pd.DataFrame(mydict)
d2

In [ ]:
#2.b.
#indexing the rows with the list of integers using loc/iloc
d2.iloc[0,1]
d2.iloc[:,3]
d2.iloc[:,1:3]

In [ ]:
#3.give different index in the data frame mydict
d2=pd.DataFrame(mydict,index=['a','b','c'])
d2

In [ ]:
#4.select the last row values

In [ ]:
#5. Create a `Series` that looks like this:

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can

In [126]:
#6.use lambda function to select the rows whose label index is even from the data frame frame3 [%=remainder, x.index%2==0]
frame3.iloc[lambda x:x.index%2==0]


Price  Sales
0     19    600
2     13    587
4     65    990

In [ ]:
#7. create Pandas Series object which has product of all the elements in a list list1 and 8
#Pandas Series support vectorization
list1=[1,2,3,4]
s=Series(list1)
s*8

In [ ]:
#8.get index and values of a series
ser1 = pd.Series({"India": "New Delhi",
                  "Japan": "Tokyo",
                  "UK": "London"})
print(ser1.index)
print(ser1.values)

In [ ]:
#9.create a dataframe with index and columns

In [ ]:
#10. get first 5 observartions from the data set medal.csv
#Download a data set medal.csv from Jigsaw LMS and load it in Python environment

In [ ]:
#endswith method:
#returns true if a string endswith the specified suffix. If not, it returns false
text="python is easy to learn."
text.endswith("easy to")


In [ ]:
text.endswith("easy to learn")

In [ ]:
text.endswith("easy to learn.")

In [ ]:
#missing values are denoted by 'Nan'
#count the missing values
d.isnull.sum()